# Generated by Django 3.2.8 on 2021-10-28 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, max_length=200, null=True, verbose_name='Комментарий к заказу')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес доставки')),
                ('delivery_date', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата доставки')),
                ('order_status', models.CharField(choices=[('Заявка обрабатывается', 'заявка обрабатывается'), ('Готовим ваш торт', 'готовим ваш торт'), ('Торт в пути', 'торт в пути'), ('Торт у вас', 'торт у вас')], db_index=True, default='Необработанный', max_length=30, verbose_name='Статус заказа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
            },
        ),
    ]
