# Generated by Django 3.2.8 on 2021-10-28 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cakesite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levels_count', models.CharField(choices=[('1', '1 уровень'), ('2', '2 уровня'), ('3', '3 уровня')], db_index=True, max_length=50, verbose_name='количество уровней')),
                ('cake_form', models.CharField(choices=[('Квадрат', 'квадрат'), ('Круг', 'круг'), ('Прямоугольник', 'прямоугольник')], db_index=True, max_length=50, verbose_name='форма торта')),
                ('topping', models.CharField(choices=[('Квадрат', 'квадрат'), ('Круг', 'круг'), ('Прямоугольник', 'прямоугольник')], db_index=True, max_length=50, verbose_name='топпинг')),
                ('berries', models.CharField(blank=True, choices=[('Ежевика', 'ежевика'), ('Малина', 'малина'), ('Голубика', 'голубика'), ('Клубника', 'клубника')], db_index=True, max_length=50, null=True, verbose_name='ягоды')),
                ('decor', models.CharField(blank=True, choices=[('Фисташки', 'фисташки'), ('Безе', 'безе'), ('Фундук', 'фундук'), ('Пекан', 'пекан'), ('Маршмеллоу', 'маршмеллоу'), ('Марципан', 'марципан')], db_index=True, max_length=50, null=True, verbose_name='декор')),
                ('inscription', models.CharField(blank=True, max_length=50, null=True, verbose_name='надпись')),
                ('promocode', models.CharField(blank=True, max_length=50, null=True, verbose_name='промокод')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cakes', to='cakesite.order', verbose_name='торт')),
            ],
            options={
                'verbose_name': 'торт',
                'verbose_name_plural': 'торты',
            },
        ),
    ]
