# Generated by Django 3.2.8 on 2021-10-28 12:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cakesite', '0002_cake'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_time',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Время доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата доставки'),
        ),
    ]
