# Generated by Django 3.2.8 on 2021-10-28 12:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cakesite', '0003_auto_20211028_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_time',
        ),
        migrations.AddField(
            model_name='order',
            name='deliver_to',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата и время доставки'),
        ),
    ]
