# Generated by Django 3.2.8 on 2021-10-28 13:12

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cakesite', '0004_auto_20211028_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='berries',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Ежевика', 'ежевика'), ('Малина', 'малина'), ('Голубика', 'голубика'), ('Клубника', 'клубника')], db_index=True, max_length=50, null=True, verbose_name='ягоды'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='decor',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Фисташки', 'фисташки'), ('Безе', 'безе'), ('Фундук', 'фундук'), ('Пекан', 'пекан'), ('Маршмеллоу', 'маршмеллоу'), ('Марципан', 'марципан')], db_index=True, max_length=50, null=True, verbose_name='декор'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cakes', to='cakesite.order', verbose_name='заказ'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='topping',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Без топпинга', 'без топпинга'), ('Белый соус', 'белый соус'), ('Карамельный сироп', 'карамельный сироп'), ('Кленовый сироп', 'кленовый сироп'), ('Клубничный сироп', 'клубничный сироп'), ('Черничный сироп', 'черничный сироп'), ('Молочный шоколад', 'молочный шоколад')], max_length=50),
        ),
    ]
