# Generated by Django 3.2.8 on 2021-10-28 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cakesite', '0005_auto_20211028_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cakes', to='cakesite.order', verbose_name='заказ'),
        ),
    ]
