# Generated by Django 3.2.8 on 2021-10-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakesite', '0006_alter_cake_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cost',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Стоимость торта'),
        ),
    ]
