# Generated by Django 3.2.8 on 2021-10-29 07:20

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cakesite', '0007_order_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='topping',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Без топпинга', 'без топпинга'), ('Белый соус', 'белый соус'), ('Карамельный сироп', 'карамельный сироп'), ('Кленовый сироп', 'кленовый сироп'), ('Клубничный сироп', 'клубничный сироп'), ('Черничный сироп', 'черничный сироп'), ('Молочный шоколад', 'молочный шоколад')], max_length=50, verbose_name='топпинг'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Заявка обрабатывается', 'заявка обрабатывается'), ('Готовим ваш торт', 'готовим ваш торт'), ('Торт в пути', 'торт в пути'), ('Торт у вас', 'торт у вас')], db_index=True, default='Заявка обрабатывается', max_length=30, verbose_name='Статус заказа'),
        ),
    ]
